### ISSUE TITLE
Consider using Grayskull

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/mapclassify-feedstock#34]
To simplify updating dependency constraints, it may be worth [configuring Grayskull in `conda-forge.yml`]( https://conda-forge.org/docs/maintainer/conda_forge_yml/#bot ) like so

```yaml
bot:
  inspection: update-grayskull
```

This way the bot will refresh dependencies during updates as well

**Comment by knaaptime** [comment]
isnt [this already the case](https://github.com/conda-forge/mapclassify-feedstock/blob/e99c3b2f1d8c1c7273f725105b469bfbea0f5d8a/conda-forge.yml#L1)?

**Comment by jGaboardi** [comment]
> isnt [this already the case](https://github.com/conda-forge/mapclassify-feedstock/blob/e99c3b2f1d8c1c7273f725105b469bfbea0f5d8a/conda-forge.yml#L1)?

@knaaptime – looks like it --> https://github.com/conda-forge/mapclassify-feedstock/blob/da3265daba003aa3397e0a57d457fe5a4a4e7111/conda-forge.yml#L1

**Comment by jakirkham** [comment]
Yeah appears it was added in PR: https://github.com/conda-forge/mapclassify-feedstock/pull/19

https://github.com/conda-forge/mapclassify-feedstock/blob/a39759247fd0ae91db8d19a92a14bad8b7f329f0/conda-forge.yml#L2-L4

Unfortunately the automerge addition by the bot ( https://github.com/conda-forge/mapclassify-feedstock/commit/06c8ea0dfa8201d61471a2ded9f53a2ef413bb04 ) made this harder to parse

https://github.com/conda-forge/mapclassify-feedstock/blob/06c8ea0dfa8201d61471a2ded9f53a2ef413bb04/conda-forge.yml#L1-L4

Would suggest using more human readable YAML to avoid confusion

**Comment by knaaptime** [comment]
cool, thanks for raising either way 


(tbh, I don't think we ever specified the yaml with that odd dictionary format. I didn't even know you could do that)

**Comment by jakirkham** [comment]
Certainly and thanks for checking! 🙏

Yeah it is the bot that made this change. Asking about it here: https://github.com/conda-forge/conda-forge-webservices/issues/688

In this case, the change could have been made without the bot. Though getting a cleaner result from the bot would also be good
